# Generated by Django 5.1.2 on 2025-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_content_remove_note_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(default=None, upload_to='notes_files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
