# Generated by Django 5.1.2 on 2025-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_file_note_subject_alter_note_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
